# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "driver" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"pass" VARCHAR NOT NULL,"driverCard" VARCHAR NOT NULL,"last_name" VARCHAR,"first_name" VARCHAR,"middle_name" VARCHAR,"phone" VARCHAR NOT NULL,"secPhone" VARCHAR NOT NULL,"comment" VARCHAR,"address" VARCHAR NOT NULL,"creation_date" DATE,"edit_date" DATE,"creator_id" BIGINT,"editor_id" BIGINT);
create unique index "idx_license_uq" on "driver" ("driverCard");
create unique index "idx_pass_uq" on "driver" ("pass");
create table "user" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"login" VARCHAR NOT NULL,"password_hash" VARCHAR(1000) NOT NULL,"last_name" VARCHAR,"first_name" VARCHAR,"middle_name" VARCHAR,"role" VARCHAR NOT NULL,"creation_date" DATE,"edit_date" DATE,"creator_id" BIGINT,"editor_id" BIGINT);
create unique index "idx_login_uq" on "user" ("login");
alter table "driver" add constraint "fk_driver_creator" foreign key("creator_id") references "user"("id") on update NO ACTION on delete NO ACTION;
alter table "driver" add constraint "fk_driver_editor" foreign key("editor_id") references "user"("id") on update NO ACTION on delete NO ACTION;
alter table "user" add constraint "fk_user_creator" foreign key("creator_id") references "user"("id") on update NO ACTION on delete NO ACTION;
alter table "user" add constraint "fk_user_editor" foreign key("editor_id") references "user"("id") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "user" drop constraint "fk_user_creator";
alter table "user" drop constraint "fk_user_editor";
alter table "driver" drop constraint "fk_driver_creator";
alter table "driver" drop constraint "fk_driver_editor";
drop table "user";
drop table "driver";

